import { useEffect, useState } from "react";
import { HelmetProvider, Helmet } from "react-helmet-async";
import { Outlet, useLoaderData } from "react-router-dom";
import { socket } from "..";
import axiosUtil from "../services";

export async function loader({ params }) {
  const data = await axiosUtil.getAllRooms();
  socket.emit("join_room", params.id);
  console.log(data.rooms);
  console.log(data.rooms.find((link) => link === params.id))
  return params.id
}
const JoinRoom = () => {
  const [userRoomName, setUserRoomName] = useState("");
  const [createdUserName, setCreatedUsername] = useState(false);
  const [message, setMessage] = useState("")
  const [messageReceived, setMessageReceived] = useState([])
  const room  = useLoaderData();
  useEffect(() => {
    socket.on("receive_message", (data) => {
        setMessageReceived(data.message)
    })
  }, [socket]);
  const handleSubmit = () => {
    setCreatedUsername(true);
  };
  const handleClick = () => {
    setMessage("")
    console.log("Something", room)
    socket.emit("send_message", { message, room })
  }
  return (
    <HelmetProvider>
      <Helmet>
        <title>codefusion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Helmet>
      <div className="pt-20 bg-blackish w-screen h-screen">
        {!createdUserName ? (
          <div className="bg-white p-8 max-w-xs mx-auto rounded-md">
            <form className="" onSubmit={handleSubmit}>
              <p className="mb-6 text-center text-lg">
                Enter your name to join the room.
              </p>
              <input
                className="focus:outline-none focus:ring focus:ring-bluish mb-2 text-lg border px-3 py-2 rounded-lg w-full"
                type="text"
                placeholder="Your name"
                value={userRoomName}
                onChange={(event) => setUserRoomName(event.target.value)}
              />
              <button
                className="bg-bluish text-white text-lg
            font-semibold py-2 mt-2 rounded-md w-full"
                type="submit"
              >
                Join
              </button>
            </form>
          </div>
        ) : (
          <div className="bg-white w-full h-96">
            <h1>{userRoomName}</h1>
              <input
              placeholder="Enter your message"
              value={message}
              onChange={(event) => setMessage(event.target.value)}
              />
              <button
               onClick={handleClick}
              >Send message</button>
              <h1>{userRoomName}: {messageReceived}</h1>
          </div>
        )}
      </div>
    </HelmetProvider>
  );
};

JoinRoom.getLayout = function getLayout(page) {
  return <main>{page}</main>;
};
export default JoinRoom;
