import { useEffect, useState } from "react";
import { HelmetProvider, Helmet } from "react-helmet-async";
import { Outlet, useLoaderData } from "react-router-dom";
import { socket } from "..";
import axiosUtil from "../services";
import Editors from "../components/Editors";
import JoinForm from "../components/JoinForm";
import Room from "../components/Room";


// export async function loader({ params }) {
//   console.log("Params", params)
//   const data = await axiosUtil.getAllRooms();
//   socket.emit("join_room", params.id);
//   console.log(data.rooms);
//   console.log(data.rooms.find((link) => link === params.id))
//   return params.id
// }


const JoinRoom = () => {
  const [createdUserName, setCreatedUsername] = useState(false);
  const [userRoomName, setUserRoomName] = useState("");
  const [session, setSession] = useState(null)

  useEffect(() => {
    setSession(sessionStorage.getItem("user_room_name"))
  })
  const room  = useLoaderData();
  return (
    <HelmetProvider>
      <Helmet>
        <title>codefusion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Helmet>
      <div className="bg-blackish h-screen">
        {(!createdUserName && !session) ? (
          <JoinForm room={room} userRoomName={userRoomName} setUserRoomName={setUserRoomName} setCreatedUsername={setCreatedUsername}/>
        ) : (
          <Room room={room} username={userRoomName || session} />
        )}
      </div>
    </HelmetProvider>
  );
};

JoinRoom.getLayout = function getLayout(page) {
  return <main>{page}</main>;
};
export default JoinRoom;
