import {Helmet, HelmetProvider} from "react-helmet-async";
import Features from "./components/Features";
import Layout from "./components/Layout";


export default function Home() {
  return (
    <HelmetProvider>
        <Helmet>
            <title>codefusion</title>
            <meta name="description" content="Generated by create next app"/>
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
            />
        </Helmet>
        <Layout>
            <Features/>
        </Layout>
    </HelmetProvider>
  );
}
