import { useState } from "react";
import Layout from "./components/Layout";
export default function Home() {
  const [room, setRoom] = useState("");

  const joinRoom = async (event) => {
    event.preventDefault();
    const roomName = room;
    const res = await fetch("/api/room", {
      body: JSON.stringify({
        roomName: roomName,
      }),
      headers: {
        "Content-Type": "application/json",
      },
      method: "POST",
    });
    await res.json();
  };

  return (
    <Layout>
      <div className="bg-blackish pt-5 w-full h-full">
        {/* <head>
        <title>codefusion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head> */}
        <main className="mt-28">
          <section className="flex flex-col lg:flex-row">
            <div
              className="flex flex-col items-center
           max-w-md mx-auto sm:max-w-xl lg:items-start
           lg:mx-10"
            >
              <div
                className="flex justify-around text-white
            text-sm items-center w-60 border rounded-3xl py-1
            border-orangish"
              >
                <div className="border border-orangish rounded-3xl px-2 bg-orangish">
                  <p>NEW</p>
                </div>
                <p>Business Plans are here! →</p>
              </div>
              <div className="mt-2 text-center lg:text-left">
                <h1 className="mb-4 text-7xl font-bold text-whitish">
                  The Better Way to Meeting
                </h1>
                <h2 className="mb-4 text-3xl text-grayish">
                  Get your team on the same page inside online meeting rooms
                  with collaborative productivity tools.
                </h2>
              </div>
              <div className="w-full">
                <form
                  onSubmit={joinRoom}
                  className="max-w-xs mx-auto flex flex-col mt-4 lg:mx-0"
                >
                  <input
                    className="border-2 focus:outline-none focus:ring
                focus:ring-activeblue text-lg p-3 rounded-md
                "
                    type="text"
                    placeholder="Enter a name for your room"
                    value={room}
                    onChange={(event) => setRoom(event.target.value)}
                  />

                  <button
                    className="bg-bluish text-white text-lg
                font-semibold py-3 mt-2 rounded-md hover:bg-blue-500"
                    type="submit"
                  >
                    Get A Room →
                  </button>
                </form>
              </div>
            </div>
            <div
              href="#document"
              className="hidden lg:flex lg:justify-center lg:items-center lg:flex-1"
            >
              <div className="relative cursor-pointer">
                <img
                  className="rounded-lg h-auto"
                  src={"/svg-export/logo2.svg"}
                  height={200}
                  width={170}
                  alt=""
                />
                <a
                  href="#document"
                  className="cursor-pointer absolute -top-40 -left-52 hover:scale-105 transition duration-300"
                >
                  <div className="relative">
                    <img
                      className="rounded-lg h-auto"
                      src={"/svg-export/document-icon.svg"}
                      height={200}
                      width={170}
                      alt=""
                    />
                  </div>
                  <div className="absolute -right-40 -bottom-7 left-20 w-full drop-shadow-lg">
                    <div className="flex px-2 py-2 items-center rounded-full bg-pink-200">
                      <div className="rounded-full bg-white p-2">
                        <img
                          className="h-auto"
                          src={"/svg-export/file-icon.svg"}
                          height={20}
                          width={20}
                          alt=""
                        />
                      </div>
                      <p className="px-2 text-pink-600 font-bold">Document</p>
                    </div>
                  </div>
                </a>
                <a
                  href="#code"
                  className="cursor-pointer absolute -bottom-40  hover:scale-105 transition duration-300"
                >
                  <div className="relative">
                    <img
                      className="rounded-lg h-auto  border-2 border-white"
                      src={"/svg-export/code-icon.svg"}
                      height={200}
                      width={170}
                      alt=""
                    />
                  </div>
                  <div className="absolute -right-40 -bottom-7 left-20 w-full drop-shadow-lg">
                    <div className="flex px-2 py-2 items-center rounded-full bg-green-200 w-28">
                      <div className="rounded-full bg-white p-2">
                        <img
                          className="h-auto"
                          src={"/svg-export/tag.svg"}
                          height={20}
                          width={20}
                          alt=""
                        />
                      </div>
                      <p className="px-2 text-green-700 font-bold">Code</p>
                    </div>
                  </div>
                </a>

                <a
                  href="#video"
                  className="cursor-pointer absolute -top-40 -right-36 hover:scale-105 transition duration-300"
                >
                  <div className="relative">
                    <div className="relative">
                      <img
                        className="rounded-lg h-auto  border-2 border-white"
                        src={"/svg-export/video.svg"}
                        height={200}
                        width={170}
                        alt=""
                      />
                    </div>
                    <div className="absolute top-20 -right-28">
                      <div className="relative">
                        <img
                          className="rounded-lg h-auto"
                          src={"/svg-export/vidmale.svg"}
                          height={200}
                          width={170}
                          alt=""
                        />
                      </div>
                      <div className="absolute -bottom-4 -left-14 flex px-2 py-2 items-center rounded-full bg-blue-200">
                        <div className="rounded-full bg-white p-2">
                          <img
                            className="h-auto"
                            src={"/svg-export/cam.svg"}
                            height={20}
                            width={20}
                            alt=""
                          />
                        </div>
                        <p className="px-2 text-bluish font-bold">Video</p>
                      </div>
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </section>
          <div
            className="mt-14 flex flex-col
          max-w-lg mx-auto sm:max-w-sm md:max-w-xl"
          >
            <img
              className="w-auto"
              src={"/svg-export/plateau.svg"}
              height={200}
              width={120}
              alt=""
            />
          </div>
          <section
            id="features"
            className="pt-24 flex flex-col bg-white items-center lg:flex-row lg:items-baseline lg:justify-evenly"
          >
            <div id="code" className="max-w-xs flex flex-col items-center">
              <div className="flex px-2 py-2 items-center rounded-full bg-green-200">
                <div className="rounded-full bg-white p-2">
                  <img
                    className="h-auto"
                    src={"/svg-export/tag.svg"}
                    height={20}
                    width={20}
                    alt=""
                  />
                </div>
                <p className="px-2 text-lg text-green-700 font-bold">Code</p>
              </div>
              <div className="max-w-xs mt-4 text-center text-5xl font-extrabold">
                <h1>Hack It Out In Code</h1>
              </div>
              <div className="mt-4 text-center text-xl text-blacklike">
                <div>
                  Jump into the code editor to pair program or help a friend to
                  debug some code.
                </div>
                <div
                  className="mt-4 uppercase text-sm font-semibold
             text-green-700 flex flex-col items-center"
                >
                  <div className="flex flex-row items-center">
                    <img
                      className="h-auto"
                      src={"/svg-export/syntax.svg"}
                      height={20}
                      width={17}
                      alt=""
                    />
                    <p className="px-3 py-2">Syntax Highlighting </p>
                  </div>
                  <div className="pl-6 flex flex-row">
                    <img
                      className="h-auto"
                      src={"/svg-export/execute.svg"}
                      height={10}
                      width={15}
                      alt=""
                    />
                    <p className="px-3">Execute Code In-Browser</p>
                  </div>
                </div>
              </div>
            </div>

            <div
              id="video"
              className="max-w-xs mt-24 flex flex-col items-center"
            >
              <div className="flex px-2 py-2 items-center rounded-full bg-blue-200">
                <div className="rounded-full bg-white p-2">
                  <img
                    className="h-auto"
                    src={"/svg-export/cam.svg"}
                    height={20}
                    width={20}
                    alt=""
                  />
                </div>
                <p className="px-2 text-lg text-bluish font-bold">Video</p>
              </div>
              <div className="mt-4 text-center text-5xl font-extrabold">
                <h1>Feel Like You are in the Room</h1>
              </div>
              <div className="mt-4 text-center text-xl text-blacklike">
                <div>
                  Hop on a video call to hash things out and talk about what you
                  are working on.
                </div>
              </div>
            </div>

            <div
              id="document"
              className="max-w-xs mt-24 flex flex-col items-center"
            >
              <div className="flex px-2 py-2 items-center rounded-full bg-pink-200">
                <div className="rounded-full bg-white p-2">
                  <img
                    className="h-auto"
                    src={"/svg-export/file-icon.svg"}
                    height={20}
                    width={20}
                    alt=""
                  />
                </div>
                <p className="px-2 text-lg text-pink-600 font-bold">Document</p>
              </div>
              <div className="mt-4 text-center text-5xl font-extrabold">
                <h1>Take Notes or Write Long-Form</h1>
              </div>
              <div className="mt-4 text-center text-xl text-blacklike">
                <div>
                  For all communication that does not require a call, chat has
                  you covered.
                </div>
              </div>
              <div
                className="mt-4 uppercase text-sm font-semibold
              text-pink-600 flex flex-col items-center"
              >
                <div className="flex flex-row items-center">
                  <img
                    className="h-auto"
                    src={"/svg-export/write.svg"}
                    height={20}
                    width={17}
                    alt=""
                  />
                  <p className="px-3 py-2">Write & Edit Together</p>
                </div>
                <div className="pl-6 flex flex-row">
                  <img
                    className="h-auto"
                    src={"/svg-export/save.svg"}
                    height={10}
                    width={15}
                    alt=""
                  />
                  <p className="px-3">Saves Automatically</p>
                </div>
              </div>
            </div>
          </section>
        </main>
      </div>
    </Layout>
  );
}
